# Generated by Django 2.2 on 2020-11-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=500)),
                ('memo', models.CharField(max_length=100)),
                ('request_method', models.CharField(max_length=10)),
                ('params', models.CharField(default={}, max_length=10000)),
                ('cookies', models.CharField(default={}, max_length=10000)),
                ('base_head', models.CharField(default={}, max_length=1000)),
                ('post_type', models.CharField(default='JSON', max_length=50)),
                ('base_body', models.CharField(default={}, max_length=10000)),
                ('base_expect', models.CharField(default={}, max_length=10000)),
                ('owner', models.CharField(default=None, max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('tt', 'method'), ('字段值类型', 'valuetype'), ('待测条件', 'condioptions'), ('发送数据类型', 'posttype')], max_length=20)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singleapi.Api')),
            ],
        ),
        migrations.CreateModel(
            name='ApiCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=100)),
                ('path', models.CharField(default='', max_length=500)),
                ('request_method', models.CharField(default='GET', max_length=10)),
                ('memo', models.CharField(default='', max_length=100)),
                ('params', models.CharField(default={}, max_length=10000)),
                ('cookies', models.CharField(default={}, max_length=10000)),
                ('head', models.CharField(blank=True, max_length=1000)),
                ('body', models.CharField(blank=True, max_length=10000)),
                ('expect', models.CharField(max_length=10000)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singleapi.Api')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
