# Generated by Django 2.2 on 2020-11-05 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('singleapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='post_type',
            field=models.CharField(choices=[('JSON', 'JSON'), ('FORM-DATA', 'FORM-DATA')], default='JSON', max_length=50),
        ),
        migrations.AddField(
            model_name='apicase',
            name='cookies',
            field=models.CharField(default={}, max_length=10000),
        ),
        migrations.AddField(
            model_name='apicase',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apicase',
            name='memo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apicase',
            name='params',
            field=models.CharField(default={}, max_length=10000),
        ),
        migrations.AddField(
            model_name='apicase',
            name='path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='apicase',
            name='request_method',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT')], default='GET', max_length=10),
        ),
        migrations.AddField(
            model_name='apicase',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
