# Generated by Django 2.2 on 2020-11-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleapi', '0002_auto_20201119_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optiondict',
            name='value',
        ),
        migrations.AddField(
            model_name='optiondict',
            name='widget',
            field=models.CharField(choices=[('复选框', 'checkbox'), ('输入框', 'input'), ('下拉框', 'select'), ('区间输入框', 'doubleinput')], default=('输入框', 'input'), max_length=100),
        ),
    ]
